### PR TITLE
include a function to get size of phrases

### PR DESCRIPTION
**Pull request by tuevo21**

### CODE REVIEW

**Comment by ljharb** [comment]
What's the use case for this method?

**Comment by tuevo21** [comment]
I think if users do multiple 'extend' calls, each with different number of
objects, they can double check each time by looking up size method. In
general, it just helps users to know how many objects are in phrases at any
point.

**Comment by ljharb** [comment]
What would they be checking though? Knowing the number of phrases doesn't tell you if they're the right ones.

**Comment by tuevo21** [comment]
You are correct - it is not necessary.

**Pull request closed without merging**
