### PR TITLE
Minor Fixes

### PR DESCRIPTION
**Pull request by ronbak**
Hi,

this merge request fixes some minor issues.
It was created with help of [Feram][repo].

If it helped to improve this repository,
please consider to [star Feram's repo][repo] to show some love! 😊

PS:
The [Feram team][feramhq] is currently working on making this technology
available for everyone. If you want to be one of the first to use it,
please sign up up for the newsletter on [feram.co].

[repo]: https://github.com/feramhq/feram
[feramhq]: https://github.com/feramhq
[feram.co]: http://feram.co

### CODE REVIEW

**Comment by ljharb** [comment]
This is not an improvement.

**Comment by ronbak** [comment]
Well, I'd call that debatable: http://stackoverflow.com/a/1406618 …
I think it's horrible.

**Comment by ljharb** [comment]
@ronbak it's less robust. `Boolean` is a global that can be overwritten - `‼` is syntax that is unbreakable, and universal across programming and discrete math.

**Comment by ronbak** [comment]
It there is a real risk that `Boolean` gets overwritten somewhere in your code, than you've got way bigger problems … =D

**Pull request closed without merging**
